version: 0.2

phases:
  install:
    commands:
      - echo "Installation des dépendances"
  build:
    commands:
      - echo "Synchronisation avec S3"
      - aws s3 sync . s3://cicd.pagnolfeuyan.com --delete
artifacts:
  files:
    - '**/*'

